"""Vietnamese descriptions for Django permission codenames.

Key format: "<app_label>.<codename>"  e.g. "accounts.view_user"
Value: human-readable Vietnamese description shown in the admin UI.
"""

PERMISSION_DESCRIPTIONS: dict[str, str] = {
    # ── accounts ─────────────────────────────────────────────────────────────
    "accounts.view_user": "Xem danh sách và thông tin người dùng",
    "accounts.add_user": "Tạo tài khoản người dùng mới",
    "accounts.change_user": "Chỉnh sửa thông tin và hồ sơ người dùng",
    "accounts.delete_user": "Xóa tài khoản người dùng khỏi hệ thống",
    "accounts.view_activitylevel": "Xem danh sách mức vận động",
    "accounts.add_activitylevel": "Thêm mức vận động mới",
    "accounts.change_activitylevel": "Chỉnh sửa thông số mức vận động",
    "accounts.delete_activitylevel": "Xóa mức vận động",
    "accounts.view_weighthistory": "Xem lịch sử cân nặng của người dùng",
    "accounts.add_weighthistory": "Ghi nhận cân nặng mới cho người dùng",
    "accounts.change_weighthistory": "Chỉnh sửa bản ghi cân nặng",
    "accounts.delete_weighthistory": "Xóa bản ghi cân nặng",
    "accounts.view_accountotp": "Xem mã OTP xác thực tài khoản",
    "accounts.add_accountotp": "Tạo mã OTP xác thực",
    "accounts.change_accountotp": "Chỉnh sửa mã OTP",
    "accounts.delete_accountotp": "Xóa mã OTP",
    "accounts.view_quotaconfig": "Xem cấu hình giới hạn lượt quét",
    "accounts.add_quotaconfig": "Tạo cấu hình giới hạn lượt quét",
    "accounts.change_quotaconfig": "Cập nhật giới hạn lượt quét cho khách vãng lai",
    "accounts.delete_quotaconfig": "Xóa cấu hình giới hạn lượt quét",
    # ── nutrients ─────────────────────────────────────────────────────────────
    "nutrients.view_food": "Xem danh sách món ăn trong cơ sở dữ liệu",
    "nutrients.add_food": "Thêm món ăn mới vào cơ sở dữ liệu",
    "nutrients.change_food": "Chỉnh sửa thông tin món ăn",
    "nutrients.delete_food": "Xóa món ăn khỏi cơ sở dữ liệu",
    "nutrients.view_ingredientphysicaldata": "Xem dữ liệu thể tích và dinh dưỡng nguyên liệu",
    "nutrients.add_ingredientphysicaldata": "Thêm dữ liệu nguyên liệu mới",
    "nutrients.change_ingredientphysicaldata": "Chỉnh sửa dữ liệu nguyên liệu",
    "nutrients.delete_ingredientphysicaldata": "Xóa dữ liệu nguyên liệu",
    "nutrients.view_healthadvicerule": "Xem quy tắc tư vấn dinh dưỡng theo mức calories",
    "nutrients.add_healthadvicerule": "Thêm quy tắc tư vấn dinh dưỡng mới",
    "nutrients.change_healthadvicerule": "Chỉnh sửa nội dung quy tắc tư vấn",
    "nutrients.delete_healthadvicerule": "Xóa quy tắc tư vấn dinh dưỡng",
    "nutrients.view_packagedfood": "Xem thực phẩm đóng gói (tra cứu barcode)",
    "nutrients.add_packagedfood": "Thêm thực phẩm đóng gói mới",
    "nutrients.change_packagedfood": "Chỉnh sửa thông tin thực phẩm đóng gói",
    "nutrients.delete_packagedfood": "Xóa thực phẩm đóng gói",
    # ── analysis ──────────────────────────────────────────────────────────────
    "analysis.view_dailylog": "Xem nhật ký dinh dưỡng hằng ngày",
    "analysis.add_dailylog": "Tạo nhật ký dinh dưỡng",
    "analysis.change_dailylog": "Chỉnh sửa nhật ký dinh dưỡng",
    "analysis.delete_dailylog": "Xóa nhật ký dinh dưỡng",
    "analysis.view_mealentry": "Xem chi tiết bữa ăn đã ghi nhận",
    "analysis.add_mealentry": "Ghi nhận bữa ăn mới vào nhật ký",
    "analysis.change_mealentry": "Chỉnh sửa thông tin bữa ăn đã ghi",
    "analysis.delete_mealentry": "Xóa bữa ăn khỏi nhật ký",
    "analysis.view_mealcomponent": "Xem thành phần dinh dưỡng từng nguyên liệu trong bữa",
    "analysis.add_mealcomponent": "Thêm thành phần nguyên liệu vào bữa ăn",
    "analysis.change_mealcomponent": "Chỉnh sửa thành phần nguyên liệu",
    "analysis.delete_mealcomponent": "Xóa thành phần nguyên liệu khỏi bữa ăn",
    # ── inference ─────────────────────────────────────────────────────────────
    "inference.view_inferencejob": "Xem trạng thái và kết quả job phân tích ảnh AI",
    "inference.add_inferencejob": "Gửi ảnh thực phẩm để phân tích dinh dưỡng bằng AI",
    "inference.change_inferencejob": "Chỉnh sửa thông tin job phân tích AI",
    "inference.delete_inferencejob": "Xóa job phân tích AI",
    "inference.view_inferenceresult": "Xem kết quả dinh dưỡng chi tiết từ AI",
    "inference.add_inferenceresult": "Tạo kết quả phân tích AI",
    "inference.change_inferenceresult": "Chỉnh sửa kết quả phân tích AI",
    "inference.delete_inferenceresult": "Xóa kết quả phân tích AI",
    "inference.view_inferencefeedback": "Xem danh sách phản hồi về độ chính xác AI",
    "inference.add_inferencefeedback": "Gửi phản hồi về kết quả phân tích AI",
    "inference.change_inferencefeedback": "Duyệt và cập nhật trạng thái phản hồi AI",
    "inference.delete_inferencefeedback": "Xóa phản hồi AI",
    # ── auth ──────────────────────────────────────────────────────────────────
    "auth.view_group": "Xem danh sách nhóm quyền",
    "auth.add_group": "Tạo nhóm quyền mới",
    "auth.change_group": "Chỉnh sửa nhóm quyền và danh sách quyền trong nhóm",
    "auth.delete_group": "Xóa nhóm quyền khỏi hệ thống",
    "auth.view_permission": "Xem toàn bộ danh sách quyền trong hệ thống",
    "auth.add_permission": "Tạo quyền tùy chỉnh mới (nâng cao)",
    "auth.change_permission": "Chỉnh sửa định nghĩa quyền (nâng cao)",
    "auth.delete_permission": "Xóa quyền khỏi hệ thống (nâng cao)",
}
