# Generated by Django 6.0.4 on 2026-05-31 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferencejob',
            name='camera_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='inferencejob',
            name='depth_map',
            field=models.FileField(blank=True, upload_to='inference/depth_maps/'),
        ),
        migrations.AddField(
            model_name='inferencejob',
            name='depth_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
