# Generated by Django 6.0.4 on 2026-06-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferencejob',
            name='camera_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='inferencejob',
            name='depth_map',
            field=models.FileField(blank=True, upload_to='inference/depth_maps/'),
        ),
        migrations.AddField(
            model_name='inferencejob',
            name='depth_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='inferencejob',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='inferencejob',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='inference/images/'),
        ),
    ]
