# Generated by Django 6.0.4 on 2026-06-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0002_inferencejob_camera_metadata_inferencejob_depth_map_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferencejob',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
