# Generated by Django 6.0.4 on 2026-06-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0003_inferencejob_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inferencejob',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='inference/images/'),
        ),
    ]
