# Generated by Django 6.0.4 on 2026-06-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0003_inferencejob_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferencejob',
            name='error_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
