# Generated by Django 6.0.4 on 2026-06-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0004_inferencejob_error_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inferencejob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('retrying', 'Retrying'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
