# Generated by Django 6.0.4 on 2026-05-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('vi_name', models.CharField(max_length=255, verbose_name='Tên tiếng Việt')),
                ('en_name', models.CharField(max_length=255, verbose_name='Tên tiếng Anh')),
                ('fdc_id', models.CharField(help_text='Mã tham chiếu USDA', max_length=50, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthAdviceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_percent', models.FloatField(help_text='Ngưỡng % TDEE tối thiểu')),
                ('max_percent', models.FloatField(help_text='Ngưỡng % TDEE tối đa')),
                ('alert_level', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Warning'), ('danger', 'Danger')], max_length=10)),
                ('advice_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IngredientPhysicalData',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('vi_name', models.CharField(max_length=255, verbose_name='Tên tiếng Việt')),
                ('en_name', models.CharField(max_length=255, verbose_name='Tên tiếng Anh')),
                ('density', models.FloatField(help_text='Khối lượng riêng (g/cm3)')),
                ('cal_per_100g', models.FloatField(verbose_name='Calories/100g')),
                ('fat_per_100g', models.FloatField(verbose_name='Fat/100g')),
                ('carb_per_100g', models.FloatField(verbose_name='Carb/100g')),
                ('protein_per_100g', models.FloatField(verbose_name='Protein/100g')),
                ('fdc_id_ref', models.CharField(blank=True, help_text='Mã tham chiếu USDA', max_length=50, null=True)),
            ],
        ),
    ]
