# Generated by Django 6.0.4 on 2026-05-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagedFood',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('barcode', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('serving_size', models.FloatField(default=100)),
                ('serving_unit', models.CharField(default='g', max_length=50)),
                ('cal_per_serving', models.FloatField(default=0)),
                ('fat_per_serving', models.FloatField(default=0)),
                ('carb_per_serving', models.FloatField(default=0)),
                ('protein_per_serving', models.FloatField(default=0)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('external_source', models.CharField(default='open_food_facts', max_length=50)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='external_source',
            field=models.CharField(default='usda', max_length=50),
        ),
        migrations.AddField(
            model_name='food',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
