# Generated by Codex on 2026-06-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrients", "0002_packagedfood_food_external_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredientphysicaldata",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
