"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-local-development-key')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

def env_list(name, default=""):
    return [item.strip() for item in os.getenv(name, default).split(",") if item.strip()]

CORS_ALLOW_ALL_ORIGINS = os.getenv('CORS_ALLOW_ALL_ORIGINS', 'False') == 'True'
CORS_ALLOWED_ORIGINS = env_list('CORS_ALLOWED_ORIGINS', 'http://localhost,http://127.0.0.1,http://localhost:3000,http://localhost:5173')
ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', 'localhost,127.0.0.1')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    # 'djangorestframework-simplejwt',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'drf_spectacular',

    'accounts.apps.AccountsConfig', # Quản lý định danh, thể trạng và OTP
    'nutrients.apps.NutrientsConfig', # Quản lý dữ liệu thực phẩm, khối lượng riêng và quy tắc lời khuyên
    'analysis.apps.AnalysisConfig', # Quản lý nhật ký người dùng và kết quả phân tích từ AI
    'inference.apps.InferenceConfig', # Điều phối pipeline AI ảnh 2D
    'reports.apps.ReportsConfig', # Thống kê dinh dưỡng và dashboard admin
    'extensions.apps.ExtensionsConfig' # Chứa lệnh khởi tạo dữ liệu
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'core.exceptions.api_exception_handler',
    # Rates consumed by per-view throttles (e.g. InferenceCreateThrottle).
    # Applied only on views that opt in via @throttle_classes.
    'DEFAULT_THROTTLE_RATES': {
        'inference_create': os.getenv('THROTTLE_INFERENCE_CREATE', '20/min'),
    },
}

# Shared cache (Redis) — backs DRF throttling so limits are enforced across all
# gunicorn workers / replicas instead of per-process.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': os.getenv('REDIS_CACHE_URL', 'redis://localhost:6379/1'),
    }
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60), # Cho người dùng dùng lâu chút
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),   # Token làm mới dùng trong 1 tuần
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,               # Quan trọng cho tính năng Logout
    'AUTH_HEADER_TYPES': ('Bearer',),
}

SPECTACULAR_SETTINGS = {
    "TITLE": "NutriLens API",
    "VERSION": "1.0.0",
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),        
        'USER': os.getenv('DB_USER'),            
        'PASSWORD': os.getenv('DB_PASSWORD'), 
        'HOST': os.getenv('DB_HOST'),  
        'PORT': os.getenv('DB_PORT'), 
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'accounts.User'

# --- EMAIL ---
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND')
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'False') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')

# --- ACCOUNTS ---
ADMIN_DEFAULT_RESET_PASSWORD = os.getenv("ADMIN_DEFAULT_RESET_PASSWORD", "NutriLens@123")

# --- CELERY ---
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://localhost:6379/0")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

# Reliability: a task is acked only after it finishes (acks_late), and is
# requeued if its worker dies mid-run — so crashes don't silently drop jobs.
# The idempotency guard in process_inference_job_task makes redelivery safe.
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
# Fair dispatch: don't let one worker prefetch a backlog of long AI tasks.
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
# Isolate the expensive AI pipeline on its own queue so it cannot starve
# lightweight tasks (e.g. emails).
CELERY_TASK_DEFAULT_QUEUE = "default"
CELERY_TASK_ROUTES = {
    "inference.tasks.process_inference_job_task": {"queue": "ai"},
}

# --- EXTERNAL SERVICES ---
EXTERNAL_API_TIMEOUT = float(os.getenv("EXTERNAL_API_TIMEOUT", "5"))
INTERNAL_API_KEY = os.getenv("INTERNAL_API_KEY", "")

AI_SERVER_URL = os.getenv("AI_SERVER_URL", "").rstrip("/")
AI_SERVER_ANALYZE_PATH = os.getenv("AI_SERVER_ANALYZE_PATH", "/analyze")
AI_SERVER_API_KEY = os.getenv("AI_SERVER_API_KEY", "")
AI_SERVER_TIMEOUT = float(os.getenv("AI_SERVER_TIMEOUT", "60"))

CLOUDINARY_CLOUD_NAME = os.getenv("CLOUDINARY_CLOUD_NAME", "")
CLOUDINARY_API_KEY = os.getenv("CLOUDINARY_API_KEY", "")
CLOUDINARY_API_SECRET = os.getenv("CLOUDINARY_API_SECRET", "")
CLOUDINARY_FOLDER = os.getenv("CLOUDINARY_FOLDER", "nutrilens/inference/jobs")
CLOUDINARY_AVATAR_FOLDER = os.getenv("CLOUDINARY_AVATAR_FOLDER", "nutrilens/users")
CLOUDINARY_UPLOAD_TIMEOUT = float(os.getenv("CLOUDINARY_UPLOAD_TIMEOUT", "30"))

OPEN_FOOD_FACTS_BASE_URL = os.getenv(
    "OPEN_FOOD_FACTS_BASE_URL",
    "https://world.openfoodfacts.org",
).rstrip("/")
OPEN_FOOD_FACTS_USER_AGENT = os.getenv(
    "OPEN_FOOD_FACTS_USER_AGENT",
    "NutriLens/1.0 (contact: admin@nutrilens.local)",
)

USDA_BASE_URL = os.getenv("USDA_BASE_URL", "https://api.nal.usda.gov/fdc/v1").rstrip("/")
USDA_API_KEY = os.getenv("USDA_API_KEY", "")
USDA_SEARCH_DATA_TYPES = env_list("USDA_SEARCH_DATA_TYPES", "Foundation,SR Legacy,Survey (FNDDS)")

GITHUB_MODELS_TOKEN = os.getenv("GITHUB_MODELS_TOKEN") or os.getenv("GITHUB_TOKEN", "")
GITHUB_MODELS_ENDPOINT = os.getenv("GITHUB_MODELS_ENDPOINT", "https://models.github.ai/inference").rstrip("/")
GITHUB_MODELS_TRANSLATION_MODEL = os.getenv("GITHUB_MODELS_TRANSLATION_MODEL", "openai/gpt-4o")
GITHUB_MODELS_TRANSLATION_TIMEOUT = float(os.getenv("GITHUB_MODELS_TRANSLATION_TIMEOUT", "10"))
