# Generated by Django 6.0.4 on 2026-05-02 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutrients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(verbose_name='Ngày ghi chép')),
                ('total_calories', models.FloatField(default=0)),
                ('total_protein', models.FloatField(default=0)),
                ('total_carbs', models.FloatField(default=0)),
                ('total_fat', models.FloatField(default=0)),
                ('total_weight', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealEntry',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('meal_time', models.DateTimeField(auto_now_add=True)),
                ('image_path', models.ImageField(upload_to='meal_images/', verbose_name='Ảnh gốc RGB')),
                ('source_type', models.CharField(default='camera', max_length=50)),
                ('total_calories', models.FloatField(default=0)),
                ('total_protein', models.FloatField(default=0)),
                ('total_carbs', models.FloatField(default=0)),
                ('total_fat', models.FloatField(default=0)),
                ('total_weight', models.FloatField(default=0)),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nutrients.food')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='analysis.dailylog')),
            ],
        ),
        migrations.CreateModel(
            name='MealComponent',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('component_name', models.CharField(max_length=255, verbose_name='Tên thành phần')),
                ('mask_path', models.ImageField(upload_to='masks/', verbose_name='Ảnh Mask')),
                ('volume', models.FloatField(verbose_name='Thể tích (cm3)')),
                ('calculated_weight', models.FloatField(editable=False, verbose_name='Khối lượng tính toán (g)')),
                ('physical_data', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nutrients.ingredientphysicaldata')),
                ('meal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='analysis.mealentry')),
            ],
        ),
    ]
