# Generated by Django 6.0.4 on 2026-05-18 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('nutrients', '0002_packagedfood'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealcomponent',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mealcomponent',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mealcomponent',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mealcomponent',
            name='protein',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mealentry',
            name='barcode',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='mealentry',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealentry',
            name='inference_job_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mealentry',
            name='is_confirmed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mealentry',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mealentry',
            name='packaged_food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nutrients.packagedfood'),
        ),
        migrations.AddField(
            model_name='mealentry',
            name='search_query',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mealcomponent',
            name='mask_path',
            field=models.ImageField(blank=True, null=True, upload_to='masks/', verbose_name='Ảnh Mask'),
        ),
        migrations.AlterField(
            model_name='mealentry',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='meal_images/', verbose_name='Ảnh gốc RGB'),
        ),
        migrations.AlterField(
            model_name='mealentry',
            name='source_type',
            field=models.CharField(choices=[('image', 'Image'), ('barcode', 'Barcode'), ('text', 'Text'), ('voice', 'Voice'), ('manual', 'Manual')], default='image', max_length=50),
        ),
    ]
